### ISSUE TITLE
Nothing happens when run the py

### ISSUE THREAD

**Issue by darkhacknet** [xbinner18/ccchk-ub#2]
Hello bro, 

I have this weird issue, when I run de .py basically nothing happens, the script is giving me the api id like this 

└─$ python3 sessionmaker.py  
147xxxxx

and that's it. Idk how to use this ! 
Please help me, thanks in advance

**Comment by sonarypt** [comment]
Indeed, you should put all your screen activities here. As I check the [sessionmaker.py](https://github.com/xbinner18/ccchk-ub/blob/main/sessionmaker.py), the script asks you for the API key and API hash first.

**Comment by darkhacknet** [comment]
> Indeed, you should put all your screen activities here. As I check the [sessionmaker.py](https://github.com/xbinner18/ccchk-ub/blob/main/sessionmaker.py), the script asks you for the API key and API hash first.

Wow.. The script dont ask me for that info.

**Comment by xbinner18** [comment]
Well this repo have two branches one to run as userbot (main), second to run as bot(botclient) if wanna deploy it as bot then u dont need to run stringsession maker to gen session for bot client u just need bot token from bot father!!!

**Comment by xbinner18** [comment]
> > Well this repo have two branches one to run as userbot (main), second to run as bot(botclient) if wanna deploy it as bot then u dont need to run stringsession maker to gen session for bot client u just need bot token from bot father!!! And api_id and api_hash
> 
> Thanks man that makes sense, but idk if Im blind, but cant see where do I need to put my bot token.

U have to put bot token api_id & hash in env create env file and then run!!
